modbus:
  baudrate: 9600
  port: /dev/ttyS0
  timeout: 3

pid:
  motor_a_b:
    Kp: 10.0
    Ki: 0.0
    Kd: 0.0
  motor_nutrisi:
    Kp: 0.0
    Ki: 0.0
    Kd: 0.0
  motor_ph:
    Kp: 1.08
    Ki: 1.54
    Kd: 0.189

setpoint:
  ec: 1800
  ph: 6.3
  pressure_kpa: 2500

uart:
  baudrate: 115200
  rx_pin: 12
  tx_pin: 13
